-- MySQL Script generated by MySQL Workbench
-- Sat Jul  4 19:20:48 2015
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema esquire_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `esquire_app` DEFAULT CHARACTER SET latin1 COLLATE latin1_spanish_ci ;
USE `esquire_app` ;

-- -----------------------------------------------------
-- Table `esquire_app`.`ct_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquire_app`.`ct_usuario` (
  `id_usuario` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `correo_electornico` VARCHAR(80) NOT NULL,
  `passwd` VARCHAR(50) NOT NULL COMMENT 'SHA1(MD5(PASSWD))',
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esquire_app`.`ct_eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquire_app`.`ct_eventos` (
  `id_evento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(120) NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `presentador` VARCHAR(250) NULL,
  `detalles` LONGTEXT NULL,
  PRIMARY KEY (`id_evento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esquire_app`.`ct_encuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquire_app`.`ct_encuesta` (
  `id_encuesta` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NOT NULL,
  `activa` TINYINT NOT NULL DEFAULT 0,
  `id_evento` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_encuesta`),
  CONSTRAINT `fk_evento_encuesta`
    FOREIGN KEY (`id_evento`)
    REFERENCES `esquire_app`.`ct_eventos` (`id_evento`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_evento_encuesta_idx` ON `esquire_app`.`ct_encuesta` (`id_evento` ASC);


-- -----------------------------------------------------
-- Table `esquire_app`.`ct_preguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquire_app`.`ct_preguntas` (
  `id_pregunta` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_encuesta` INT UNSIGNED NOT NULL,
  `pregunta` VARCHAR(250) NOT NULL,
  `activa` TINYINT NOT NULL DEFAULT 0,
  `fecha_publicacion` DATETIME NOT NULL,
  PRIMARY KEY (`id_pregunta`),
  CONSTRAINT `fk_pregunta_encuesta`
    FOREIGN KEY (`id_encuesta`)
    REFERENCES `esquire_app`.`ct_encuesta` (`id_encuesta`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_pregunta_encuesta_idx` ON `esquire_app`.`ct_preguntas` (`id_encuesta` ASC);


-- -----------------------------------------------------
-- Table `esquire_app`.`ct_respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquire_app`.`ct_respuesta` (
  `id_respuesta` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_pregunta` INT UNSIGNED NOT NULL,
  `respuesta` VARCHAR(100) NOT NULL,
  `valor` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_respuesta`),
  CONSTRAINT `fk_respuesta_pregunta`
    FOREIGN KEY (`id_pregunta`)
    REFERENCES `esquire_app`.`ct_preguntas` (`id_pregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_respuesta_pregunta_idx` ON `esquire_app`.`ct_respuesta` (`id_pregunta` ASC);


-- -----------------------------------------------------
-- Table `esquire_app`.`ht_resultado_encuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquire_app`.`ht_resultado_encuesta` (
  `id_resultado_encuesta` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_respuesta` INT UNSIGNED NOT NULL,
  `segmento` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_resultado_encuesta`),
  CONSTRAINT `fk_respuesta`
    FOREIGN KEY (`id_respuesta`)
    REFERENCES `esquire_app`.`ct_respuesta` (`id_respuesta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_respuesta_idx` ON `esquire_app`.`ht_resultado_encuesta` (`id_respuesta` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `esquire_app`.`ct_usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `esquire_app`;
INSERT INTO `esquire_app`.`ct_usuario` (`id_usuario`, `nombre`, `correo_electornico`, `passwd`) VALUES ('ioncom', 'ioncom', 'miguel@ioncom.com.mx', '1565113e38aa620557e05615a84e1034f6e153ce');

COMMIT;

